[ { created_at: 'Sun Oct 08 21:46:37 +0000 2017',
id: 917144224197423100,
id_str: '917144224197423105',
text: 'my 2nd tweet is even better!',
truncated: false,
entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
 { id: 917143346610569200,
   id_str: '917143346610569218',
   name: 'gregor lad',
   screen_name: 'GregorLad',
   location: '',
   description: '',
   url: null,
   entities: [Object],
   protected: false,
   followers_count: 0,
   friends_count: 44,
   listed_count: 0,
   created_at: 'Sun Oct 08 21:43:08 +0000 2017',
   favourites_count: 0,
   utc_offset: -25200,
   time_zone: 'Pacific Time (US & Canada)',
   geo_enabled: false,
   verified: false,
   statuses_count: 2,
   lang: 'en',
   contributors_enabled: false,
   is_translator: false,
   is_translation_enabled: false,
   profile_background_color: 'F5F8FA',
   profile_background_image_url: null,
   profile_background_image_url_https: null,
   profile_background_tile: false,
   profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
   profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
   profile_link_color: '1DA1F2',
   profile_sidebar_border_color: 'C0DEED',
   profile_sidebar_fill_color: 'DDEEF6',
   profile_text_color: '333333',
   profile_use_background_image: true,
   has_extended_profile: false,
   default_profile: true,
   default_profile_image: true,
   following: false,
   follow_request_sent: false,
   notifications: false,
   translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 0,
favorite_count: 0,
favorited: false,
retweeted: false,
lang: 'en' },
{ created_at: 'Sun Oct 08 21:46:26 +0000 2017',
id: 917144179536465900,
id_str: '917144179536465920',
text: 'my first tweet rocks!',
truncated: false,
entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
 { id: 917143346610569200,
   id_str: '917143346610569218',
   name: 'gregor lad',
   screen_name: 'GregorLad',
   location: '',
   description: '',
   url: null,
   entities: [Object],
   protected: false,
   followers_count: 0,
   friends_count: 44,
   listed_count: 0,
   created_at: 'Sun Oct 08 21:43:08 +0000 2017',
   favourites_count: 0,
   utc_offset: -25200,
   time_zone: 'Pacific Time (US & Canada)',
   geo_enabled: false,
   verified: false,
   statuses_count: 2,
   lang: 'en',
   contributors_enabled: false,
   is_translator: false,
   is_translation_enabled: false,
   profile_background_color: 'F5F8FA',
   profile_background_image_url: null,
   profile_background_image_url_https: null,
   profile_background_tile: false,
   profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
   profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
   profile_link_color: '1DA1F2',
   profile_sidebar_border_color: 'C0DEED',
   profile_sidebar_fill_color: 'DDEEF6',
   profile_text_color: '333333',
   profile_use_background_image: true,
   has_extended_profile: false,
   default_profile: true,
   default_profile_image: true,
   following: false,
   follow_request_sent: false,
   notifications: false,
   translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 0,
favorite_count: 0,
favorited: false,
retweeted: false,
lang: 'en' } ]